---
# default is etc/utc in build 20141129 [http://cloud.centos.org/centos/7/images/]
- name: set timezone to etc/utc
  sudo: yes
  file:
    src: /usr/share/zoneinfo/Etc/UTC
    dest: /etc/localtime
    state: link
    force: yes

# add hosts to /etc/hosts
- name: configure hosts file
  sudo: yes
  lineinfile:
    dest: /etc/hosts
    line: "{{ hostvars[item].ansible_default_ipv4.address }} {{ item }}{% if use_host_domain %} {{ item }}.{{ host_domain}}{% endif %}"
    state: present
  when: hostvars[item].ansible_default_ipv4.address is defined and item != 'localhost'
  with_items: groups['all']

# add default IPv4 address to hostname (if not already there)
- name: add default ipv4 to hosts
  sudo: yes
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ ansible_default_ipv4.address }} {{ ansible_hostname }}{% if use_host_domain %} {{ ansible_fqdn }}{% endif %}$"
    line: "{{ ansible_default_ipv4.address }} {{ ansible_hostname }}{% if use_host_domain %} {{ ansible_fqdn }}{% endif %}"
    state: present

# remove loopback addresses pointing at hostname
- name: clean hosts file
  sudo: yes
  lineinfile:
    dest: /etc/hosts
    regexp: "{{ item }}"
    state: absent
  when: inventory_hostname != 'localhost'
  with_items:
    - '^127\.0\.0\.1(\s+){{ inventory_hostname }}.*'
    - '^::1(\s+){{ inventory_hostname }}.*'
    - '^127\.0\.0\.1(\s+){{ ansible_hostname }}.*'
    - '^::1(\s+){{ ansible_hostname }}.*'

- name: install system utilities
  sudo: yes
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - httpd-tools
    - nc
    - openssh
  tags:
    - bootstrap

- name: disable firewalld
  sudo: yes
  service:
    name: firewalld
    enabled: false
    state: stopped

- name: enable EPEL repo
  sudo: yes
  yum:
    name: epel-release
    state: latest

- name: install pip
  sudo: yes
  yum:
    name: python-pip
    state: latest

- name: update setuptools and pip
  sudo: yes
  pip:
    name: "{{ item.name }}"
    state: latest
  with_items:
    - name: pip
    - name: setuptools

- name: install distributive
  sudo: yes
  yum:
    name: "https://bintray.com/artifact/download/ciscocloud/rpm/distributive-0.1.2-1.el7.centos.x86_64.rpm"
    state: present
  tags:
    - distributive

- include: users.yml
- include: ssl.yml
